### ISSUE TITLE
git exercise : git push

### ISSUE THREAD

**Issue by WandrilleD** [sib-swiss/reproducible-analysis-training#1]
in https://sib-swiss.github.io/reproducible-analysis/git_pages_zenodo.html

When pushing to the remote repository, the command you give is:
`git push -u origin main`

But the branch is "master" instead of "main" by default now I think.
Also, I think it could be useful to mention that the expected password there is the OATH token.

**Comment by GeertvanGeest** [comment]
I think the default default branch name depends on the git version and/or settings, which is 'main' for more recent versions of git. I'll add the line 

```bash
git branch -m main
``` 

In principle, people should have set this up while following the course preparations. I'll add a redirection to make sure they've set up a https connection.
